In [1]:
import pandas as pd
import numpy as np

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [2]:
crop = pd.read_csv(
    "../dataset/raw/crop_production.csv"
)

print(crop.shape)

crop.head()

(345336, 8)

,State,District,Crop,Crop_Year,Season,Area,Production,Yield
0,Andaman and Nicobar Island,NICOBARS,Arecanut,2007,Kharif,2439.6,3415.0,1.40
1,Andaman and Nicobar Island,NICOBARS,Arecanut,2007,Rabi,1626.4,2277.0,1.40
2,Andaman and Nicobar Island,NICOBARS,Arecanut,2008,Autumn,4147.0,3060.0,0.74
3,Andaman and Nicobar Island,NICOBARS,Arecanut,2008,Summer,4147.0,2660.0,0.64
4,Andaman and Nicobar Island,NICOBARS,Arecanut,2009,Autumn,4153.0,3120.0,0.75

In [3]:
print(crop.isnull().sum())

State            0
District         0
Crop             9
Crop_Year        0
Season           0
Area             0
Production    4948
Yield            0
dtype: int64

In [4]:
crop_clean = crop.dropna(
    subset=["Production", "Crop"]
)

print(crop_clean.shape)

(340383, 8)

In [5]:
crop_clean.columns = (
    crop_clean.columns
    .str.strip()
    .str.lower()
)

print(crop_clean.columns.tolist())

['state', 'district', 'crop', 'crop_year', 'season', 'area', 'production', 'yield']

In [6]:
rainfall = pd.read_csv(
    "../dataset/raw/rainfall.csv",
    sep=";"
)

print(rainfall.shape)

rainfall.head()

(8790, 34)

,state,district,month,1st,2nd,3rd,4th,5th,6th,7th,...,22nd,23rd,24th,25th,26th,27th,28th,29th,30th,31st
0,Andaman & Nicobar,Nicobars,1,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
1,Andaman & Nicobar,North And Middle Andaman,1,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2,Andaman & Nicobar,South Andamans,1,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
3,Andhra Pradesh,Anantapur,1,0.379965,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.205834,0.671002,0.028994,0.0,0.0,0.0
4,Andhra Pradesh,Chittoor,1,14.144900,0.857263,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.615237,0.925098,0.507623,0.424843,0.737394,0.0,0.0,0.0

In [8]:
daily_cols = [
    '1st','2nd','3rd','4th','5th','6th','7th',
    '8th','9th','10th','11th','12th','13th',
    '14th','15th','16th','17th','18th','19th',
    '20th','21st','22nd','23rd','24th','25th',
    '26th','27th','28th','29th','30th','31st'
]

rainfall["monthly_rainfall"] = (
    rainfall[daily_cols]
    .sum(axis=1)
)

print(
    rainfall[
        ["state", "district", "month", "monthly_rainfall"]
    ].head()
)

               state                  district  month  monthly_rainfall
0  Andaman & Nicobar                  Nicobars      1          0.000000
1  Andaman & Nicobar  North And Middle Andaman      1          0.000000
2  Andaman & Nicobar            South Andamans      1          0.000000
3     Andhra Pradesh                 Anantapur      1          2.609365
4     Andhra Pradesh                  Chittoor      1         26.160305

In [9]:
rainfall_clean = rainfall[
    [
        "state",
        "district",
        "month",
        "monthly_rainfall"
    ]
]

In [10]:
rainfall_clean.columns = (
    rainfall_clean.columns
    .str.strip()
    .str.lower()
)

print(rainfall_clean.columns.tolist())

['state', 'district', 'month', 'monthly_rainfall']

In [11]:
rainfall_clean["district"] = (
    rainfall_clean["district"]
    .str.strip()
    .str.lower()
)

rainfall_clean["state"] = (
    rainfall_clean["state"]
    .str.strip()
    .str.lower()
)

print("Rainfall Standardization Complete")

Rainfall Standardization Complete

In [12]:
rainfall_final = (
    rainfall_clean
    .groupby(
        ["state", "district"]
    )["monthly_rainfall"]
    .mean()
    .reset_index()
)

print(rainfall_final.shape)

rainfall_final.head()

(863, 3)

               state                  district  monthly_rainfall
0  andaman & nicobar                   nicobar               0.0
1  andaman & nicobar                  nicobars               0.0
2  andaman & nicobar    north & middle andaman               0.0
3  andaman & nicobar  north and middle andaman               0.0
4  andaman & nicobar             south andaman               0.0

In [13]:
population = pd.read_csv(
    "../dataset/raw/population.csv"
)

print(population.shape)

population.head()

(610, 7)

,Ranking,District,State,Population,Growth,Sex-Ratio,Literacy
0,1,Thane,Maharashtra,"11,060,148",36.01 %,886,84.53
1,2,North Twenty Four Parganas,West Bengal,"10,009,781",12.04 %,955,84.06
2,3,Bangalore,Karnataka,"9,621,551",47.18 %,916,87.67
3,4,Pune,Maharashtra,"9,429,408",30.37 %,915,86.15
4,5,Mumbai Suburban,Maharashtra,"9,356,962",8.29 %,860,89.91

In [14]:
print(population.columns.tolist())

['Ranking', 'District', 'State', 'Population', 'Growth', 'Sex-Ratio', 'Literacy']

In [15]:
population.columns = (
    population.columns
    .str.strip()
)

print(population.columns.tolist())

['Ranking', 'District', 'State', 'Population', 'Growth', 'Sex-Ratio', 'Literacy']

In [16]:
population["Population"] = (
    population["Population"]
    .str.replace(",", "", regex=False)
    .astype(int)
)

population["Growth"] = (
    population["Growth"]
    .str.replace("%", "", regex=False)
    .astype(float)
)

In [18]:
print(population.columns.tolist())

['Ranking', 'District', 'State', 'Population', 'Growth', 'Sex-Ratio', 'Literacy']

In [19]:
population_clean = population[
    [
        "District",
        "State",
        "Population",
        "Growth",
        "Literacy"
    ]
]

population_clean.head()

                     District        State  Population  Growth  Literacy
0                       Thane  Maharashtra    11060148   36.01     84.53
1  North Twenty Four Parganas  West Bengal    10009781   12.04     84.06
2                   Bangalore    Karnataka     9621551   47.18     87.67
3                        Pune  Maharashtra     9429408   30.37     86.15
4             Mumbai Suburban  Maharashtra     9356962    8.29     89.91

In [20]:
population_clean.columns = (
    population_clean.columns
    .str.strip()
    .str.lower()
)

print(population_clean.columns.tolist())

['district', 'state', 'population', 'growth', 'literacy']

In [21]:
population_clean["district"] = (
    population_clean["district"]
    .str.strip()
    .str.lower()
)

population_clean["state"] = (
    population_clean["state"]
    .str.strip()
    .str.lower()
)

print("Population Standardization Complete")

Population Standardization Complete

In [22]:
crop_pop = pd.merge(
    crop_clean,
    population_clean,
    on=["state", "district"],
    how="inner"
)

print(crop_pop.shape)

crop_pop.head()

(0, 11)

Empty DataFrame
Columns: [state, district, crop, crop_year, season, area, production, yield, population, growth, literacy]
Index: []

In [23]:
final_dataset = pd.merge(
    crop_pop,
    rainfall_final,
    on=["state", "district"],
    how="inner"
)

print(final_dataset.shape)

final_dataset.head()

(0, 12)

Empty DataFrame
Columns: [state, district, crop, crop_year, season, area, production, yield, population, growth, literacy, monthly_rainfall]
Index: []

In [24]:
def normalize_text(x):
    return (
        str(x)
        .lower()
        .strip()
        .replace("&", "and")
        .replace("-", " ")
        .replace(".", "")
    )

crop_clean["district"] = crop_clean["district"].apply(normalize_text)
crop_clean["state"] = crop_clean["state"].apply(normalize_text)

rainfall_final["district"] = rainfall_final["district"].apply(normalize_text)
rainfall_final["state"] = rainfall_final["state"].apply(normalize_text)

population_clean["district"] = population_clean["district"].apply(normalize_text)
population_clean["state"] = population_clean["state"].apply(normalize_text)

print("Normalization Complete")

Normalization Complete

In [25]:
crop_districts = set(crop_clean["district"].unique())

rain_districts = set(rainfall_final["district"].unique())

pop_districts = set(population_clean["district"].unique())

print(
    "Crop districts:",
    len(crop_districts)
)

print(
    "Rain districts:",
    len(rain_districts)
)

print(
    "Population districts:",
    len(pop_districts)
)

print(
    "Common districts:",
    len(
        crop_districts &
        rain_districts &
        pop_districts
    )
)

Crop districts: 707
Rain districts: 849
Population districts: 604
Common districts: 508

In [26]:
crop_pop = pd.merge(
    crop_clean,
    population_clean,
    on=["state", "district"],
    how="inner"
)

print(crop_pop.shape)

(248743, 11)

In [27]:
final_dataset = pd.merge(
    crop_pop,
    rainfall_final,
    on=["state", "district"],
    how="inner"
)

print(final_dataset.shape)

final_dataset.head()

(243590, 12)

,state,district,crop,crop_year,season,area,production,yield,population,growth,literacy,monthly_rainfall
0,andhra pradesh,anantapur,Arecanut,2000,Whole Year,252.0,696.0,2.76,4081148,12.1,63.57,61.666743
1,andhra pradesh,anantapur,Arecanut,2001,Whole Year,257.0,430.0,1.67,4081148,12.1,63.57,61.666743
2,andhra pradesh,anantapur,Arecanut,2002,Whole Year,263.0,379.0,1.44,4081148,12.1,63.57,61.666743
3,andhra pradesh,anantapur,Arecanut,2003,Whole Year,266.0,189.0,0.71,4081148,12.1,63.57,61.666743
4,andhra pradesh,anantapur,Arecanut,2005,Whole Year,268.0,214.0,0.80,4081148,12.1,63.57,61.666743

In [28]:
final_dataset["demand"] = (
    final_dataset["population"] * 0.002
)

In [29]:
final_dataset["risk_level"] = pd.cut(
    final_dataset["yield"],
    bins=[0, 1000, 3000, float("inf")],
    labels=["High", "Medium", "Low"]
)

In [30]:
final_dataset.to_csv(
    "../dataset/processed/final_dataset.csv",
    index=False
)

print("Final Dataset Saved")

Final Dataset Saved

In [31]:
final_dataset["demand"] = (
    final_dataset["population"] * 0.002
)

final_dataset[
    ["population", "demand"]
].head()

   population    demand
0     4081148  8162.296
1     4081148  8162.296
2     4081148  8162.296
3     4081148  8162.296
4     4081148  8162.296

In [32]:
final_dataset["risk_level"] = pd.cut(
    final_dataset["yield"],
    bins=[0, 1000, 3000, float("inf")],
    labels=["High", "Medium", "Low"]
)

final_dataset[
    ["yield", "risk_level"]
].head()

   yield risk_level
0   2.76       High
1   1.67       High
2   1.44       High
3   0.71       High
4   0.80       High

In [33]:
final_dataset.to_csv(
    "../dataset/processed/final_dataset.csv",
    index=False
)

print("Final Dataset Saved Successfully")

Final Dataset Saved Successfully

In [34]:
print(final_dataset.shape)

print("\nColumns:\n")

print(final_dataset.columns.tolist())

(243590, 14)

Columns:

['state', 'district', 'crop', 'crop_year', 'season', 'area', 'production', 'yield', 'population', 'growth', 'literacy', 'monthly_rainfall', 'demand', 'risk_level']