## Import Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.ensemble import (
    RandomForestRegressor,
    RandomForestClassifier
)

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    accuracy_score,
    classification_report,
    confusion_matrix
)

from xgboost import (
    XGBRegressor,
    XGBClassifier
)

import joblib

print("Libraries Loaded")

Libraries Loaded

## Final Dataset

In [2]:
data = pd.read_csv(
    "../dataset/processed/final_dataset.csv"
)

print(data.shape)

data.head()

(243590, 14)

,state,district,crop,crop_year,season,area,production,yield,population,growth,literacy,monthly_rainfall,demand,risk_level
0,andhra pradesh,anantapur,Arecanut,2000,Whole Year,252.0,696.0,2.76,4081148,12.1,63.57,61.666743,8162.296,High
1,andhra pradesh,anantapur,Arecanut,2001,Whole Year,257.0,430.0,1.67,4081148,12.1,63.57,61.666743,8162.296,High
2,andhra pradesh,anantapur,Arecanut,2002,Whole Year,263.0,379.0,1.44,4081148,12.1,63.57,61.666743,8162.296,High
3,andhra pradesh,anantapur,Arecanut,2003,Whole Year,266.0,189.0,0.71,4081148,12.1,63.57,61.666743,8162.296,High
4,andhra pradesh,anantapur,Arecanut,2005,Whole Year,268.0,214.0,0.80,4081148,12.1,63.57,61.666743,8162.296,High

## Categorial Columns

In [3]:
label_encoders = {}

categorical_cols = [
    "state",
    "district",
    "crop",
    "season"
]

for col in categorical_cols:
    
    le = LabelEncoder()
    
    data[col] = le.fit_transform(
        data[col]
    )
    
    label_encoders[col] = le

print("Encoding Complete")

data.head()

Encoding Complete

,state,district,crop,crop_year,season,area,production,yield,population,growth,literacy,monthly_rainfall,demand,risk_level
0,0,15,0,2000,4,252.0,696.0,2.76,4081148,12.1,63.57,61.666743,8162.296,High
1,0,15,0,2001,4,257.0,430.0,1.67,4081148,12.1,63.57,61.666743,8162.296,High
2,0,15,0,2002,4,263.0,379.0,1.44,4081148,12.1,63.57,61.666743,8162.296,High
3,0,15,0,2003,4,266.0,189.0,0.71,4081148,12.1,63.57,61.666743,8162.296,High
4,0,15,0,2005,4,268.0,214.0,0.80,4081148,12.1,63.57,61.666743,8162.296,High

## Prediction Dataset

In [4]:
X_demand = data[
    [
        "state",
        "district",
        "crop",
        "crop_year",
        "season",
        "area",
        "production",
        "yield",
        "population",
        "growth",
        "literacy",
        "monthly_rainfall"
    ]
]

y_demand = data["demand"]

print(X_demand.shape)
print(y_demand.shape)

(243590, 12)
(243590,)

## Demand

In [6]:
X_train_d, X_test_d, y_train_d, y_test_d = train_test_split(
    X_demand,
    y_demand,
    test_size=0.2,
    random_state=42
)

print(X_train_d.shape)
print(X_test_d.shape)

(194872, 12)
(48718, 12)

## Random Forest Regressor

In [7]:
rf_regressor = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_regressor.fit(
    X_train_d,
    y_train_d
)

print("Random Forest Regressor Trained")

Random Forest Regressor Trained

## Demand Prediction

In [8]:
y_pred_d = rf_regressor.predict(
    X_test_d
)

print(
    "MAE:",
    mean_absolute_error(
        y_test_d,
        y_pred_d
    )
)

print(
    "RMSE:",
    np.sqrt(
        mean_squared_error(
            y_test_d,
            y_pred_d
        )
    )
)

print(
    "R2 Score:",
    r2_score(
        y_test_d,
        y_pred_d
    )
)

MAE: 0.0007993657477425928
RMSE: 0.17643723982975357
R2 Score: 0.9999999962913809

## Demand Model

In [9]:
joblib.dump(
    rf_regressor,
    "../models/demand_prediction_model.pkl"
)

print("Demand Model Saved")

Demand Model Saved

## Risk dataset

In [11]:
X_risk = data[
    [
        "state",
        "district",
        "crop",
        "crop_year",
        "season",
        "area",
        "production",
        "population",
        "growth",
        "literacy",
        "monthly_rainfall"
    ]
]

y_risk = data["risk_level"]

print(X_risk.shape)
print(y_risk.shape)

(243590, 11)
(243590,)

## Risks Labels

In [12]:
risk_encoder = LabelEncoder()

y_risk = risk_encoder.fit_transform(
    y_risk
)

print("Risk Labels Encoded")

Risk Labels Encoded

## Test Split (Risk)

In [13]:
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X_risk,
    y_risk,
    test_size=0.2,
    random_state=42
)

print(X_train_r.shape)
print(X_test_r.shape)

(194872, 11)
(48718, 11)

## Random Forest Classifier

In [14]:
rf_classifier = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_classifier.fit(
    X_train_r,
    y_train_r
)

print("Random Forest Classifier Trained")

Random Forest Classifier Trained

## Risk Levels Prediction

In [15]:
y_pred_r = rf_classifier.predict(
    X_test_r
)

print(
    "Accuracy:",
    accuracy_score(
        y_test_r,
        y_pred_r
    )
)

Accuracy: 0.9992815797036003

## Classification Report

In [16]:
print(
    classification_report(
        y_test_r,
        y_pred_r
    )
)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     48152
           1       0.99      1.00      0.99       343
           2       0.86      0.82      0.84        22
           3       0.97      0.89      0.93       201

    accuracy                           1.00     48718
   macro avg       0.95      0.93      0.94     48718
weighted avg       1.00      1.00      1.00     48718

In [17]:
joblib.dump(
    rf_classifier,
    "../models/risk_classification_model.pkl"
)

print("Risk Classification Model Saved")

Risk Classification Model Saved